import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ReactNode } from "react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "LocateX",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
  {
    const session = await auth();
    return (
      <html lang="en" className={`${poppins.className} antialiased`}>
        <SessionProvider session={session}>
          <body>
            {children}
            <Toaster />
          </body>
        </SessionProvider>
      </html>
    );
  }
};
export default RootLayout;
